### ISSUE TITLE
image does not repaint after loading a another image using image.file_name="file"

### ISSUE THREAD

**Issue by petersnoek** [williamwilling/luagui#1]
-- example code
require "gui"

local window = gui.create_window()
window.title = "File Dialog Demo"

local button = window:add_button()
button.x = 10
button.y = 10
button.text = "Load image"

local image = window:add_image()
image.file_name = "logo.png"

--local text_box = window:add_text_box()
--text_box.multiline = true
--text_box.width = window.width
--text_box.height = window.height

local file_dialog = window:create_file_dialog()

function button:on_click()
  if file_dialog:open() then
    image.file_name = file_dialog.file_name
    image.x = image.x + 1
  end
end

gui.run()

**Comment by williamwilling** [comment]
Fixed in  ad709eecf957fe9dd2ee54957a2b0c145892dd4b.
