### ISSUE TITLE
window needs exposed "repaint" function

### ISSUE THREAD

**Issue by petersnoek** [williamwilling/luagui#2]
I would like to be able to manually repaint a window.

**Comment by williamwilling** [comment]
Could you tell me what you need it for?

Repainting seems like an implementation detail to me and including it goes against the [goals](https://github.com/williamwilling/luagui#lua-gui) of being easy to use and not feeling like a wrapper. If at all possible, I'd like to tackle the problem you are currently trying to resolve by repainting manually.
