### ISSUE TITLE
wx required

### ISSUE THREAD

**Issue by james2doyle** [williamwilling/luagui#3]
Hey there. I want to play with this, but it seems to require wxLua to be installed?

I tried to follow the instructions for building wxLua but they are horrendous. Any hints as to what steps you took to install it?

**Comment by williamwilling** [comment]
I'm using ZeroBrane Studio which has wxLua built into it. ZeroBrane is an excellent, free IDE for Lua. http://studio.zerobrane.com/

**Comment by james2doyle** [comment]
Ok thanks for the info
