### ISSUE TITLE
button:destroy() does not work when a timer object exists

### ISSUE THREAD

**Issue by petersnoek** [williamwilling/luagui#4]
@williamwilling : I have created a form with a button. When the user clicks the button, the button is destroyed using button:destroy().
This work fine, except when a timer object is created. Then, the destroy function does not work anymore.

Example code:

require "gui"

local window = gui.create_window()
window.title = "Button Demo"

local button1 = window:add_button()
button1.x = 10
button1.y = 10
button1.text = "Button1"

-- remove the two lines below to make sure 'destroy' works
local timer = gui:create_timer()
timer.interval = 1

function button1:on_click()
  button1:destroy()
  print('destroy')
end

-- comment

gui.run()

**Comment by williamwilling** [comment]
Fixed in fed58c26e6c4dec25438e69409d071fc1ac7e063.

**Comment by petersnoek** [comment]
Will this fix be published in version 5 of LuaGui? Current version is 4.
