### ISSUE TITLE
Making an executable

### ISSUE THREAD

**Issue by X-Raym** [williamwilling/luagui#5]
Hi,

just curious, how would you compile a lua programm made with LuaGui into a windows .exe or macOS dmg ? Would you use LuaDist ? Or is it somthing ZeroBrain can handle ?

Thanks !

**Comment by FreddieOffice** [comment]
i know this is old but you can use srlua or luastatic or luapak

**Comment by X-Raym** [comment]
@FreddieOffice Ok, I'll have to explore this at some point. Thx!
